export type SeedAssessmentQuestion = {
  order: number;
  prompt: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
};

export const MANUAL_ASSESSMENTS: Record<number, SeedAssessmentQuestion[]> = {
  1: [
    {
      order: 1,
      prompt: "What ultimately secures the believer's covenant relationship with God?",
      options: ["Perfect human consistency", "God's faithfulness", "Religious achievement", "Emotional certainty"],
      correctIndex: 1,
      explanation: "A biblical covenant is initiated and guaranteed by God, so the relationship rests on His faithfulness rather than human consistency.",
    },
    {
      order: 2,
      prompt: "What was a central purpose of the Old Covenant Law?",
      options: ["To reveal sin and humanity's need for Christ", "To make salvation possible through effort", "To remove the need for grace", "To guarantee righteousness by rule-keeping"],
      correctIndex: 0,
      explanation: "The Law revealed God's holiness, exposed sin, and showed humanity's need for a Savior; it could diagnose the problem but could not save.",
    },
    {
      order: 3,
      prompt: "Which statement best describes grace in the New Covenant?",
      options: ["Grace lowers God's standard", "Grace only overlooks failure", "Grace forgives and empowers transformation", "Grace makes obedience unnecessary"],
      correctIndex: 2,
      explanation: "The manual presents grace as both God's unearned favor and His empowering provision for transformed living.",
    },
    {
      order: 4,
      prompt: "How does a believer receive righteousness before God?",
      options: ["By outperforming other believers", "By receiving it as a gift through faith", "By eliminating every weakness first", "By completing enough religious duties"],
      correctIndex: 1,
      explanation: "Righteousness is a gift received through faith. Right behavior flows from that standing; it does not create it.",
    },
    {
      order: 5,
      prompt: "What does living from rest mean?",
      options: ["Avoiding all responsibility", "Waiting passively for circumstances to change", "Depending on Christ's sufficiency while responding in faith", "Refusing to make practical decisions"],
      correctIndex: 2,
      explanation: "Biblical rest is active dependence on God and confidence in Christ's finished work, not inactivity.",
    },
  ],
  2: [
    {
      order: 1,
      prompt: "What is the New Birth?",
      options: ["A commitment to improve old habits", "A new spiritual life imparted by God", "A public title earned through service", "A temporary emotional experience"],
      correctIndex: 1,
      explanation: "The New Birth is a supernatural work of God that begins a genuinely new spiritual reality.",
    },
    {
      order: 2,
      prompt: "How does the manual describe the three dimensions of a person?",
      options: ["Mind, ambition, and influence", "Belief, behavior, and belonging", "Spirit, soul, and body", "Past, present, and future"],
      correctIndex: 2,
      explanation: "The believer is a spirit, has a soul, and lives in a body. Each dimension must be understood and aligned with truth.",
    },
    {
      order: 3,
      prompt: "What happened to the old man through union with Christ?",
      options: ["It was crucified with Christ", "It became an equal second nature", "It was strengthened through discipline", "It remained the believer's true identity"],
      correctIndex: 0,
      explanation: "The old unregenerate identity was crucified with Christ; the continuing struggle is between New Creation truth and unrenewed thinking.",
    },
    {
      order: 4,
      prompt: "What does it mean to be in Christ?",
      options: ["To imitate Christ from a spiritual distance", "To earn acceptance through performance", "To share His position, life, and standing through union", "To avoid ordinary responsibilities"],
      correctIndex: 2,
      explanation: "Being in Christ describes union with Him and participation in the standing and blessings He has secured.",
    },
    {
      order: 5,
      prompt: "How should sonship shape Christian service?",
      options: ["Serve to earn a place in God's family", "Serve from acceptance as a child of God", "Serve only when publicly recognized", "Serve without receiving correction"],
      correctIndex: 1,
      explanation: "Believers serve faithfully from sonship and acceptance, not in order to earn sonship.",
    },
  ],
  3: [
    {
      order: 1,
      prompt: "What role does the written Word serve in Christian life?",
      options: ["It offers optional inspiration without authority", "It provides the foundation and standard for faith and practice", "It matters only to teachers", "It replaces dependence on the Holy Spirit"],
      correctIndex: 1,
      explanation: "The written Word establishes the foundation, structure, and standard for Christian belief and practice.",
    },
    {
      order: 2,
      prompt: "What is biblical confession?",
      options: ["Ignoring difficult circumstances", "Repeating words to control outcomes", "Verbal agreement with God's truth", "Speaking only about personal feelings"],
      correctIndex: 2,
      explanation: "Biblical confession gives expression to faith by agreeing verbally with what God has spoken.",
    },
    {
      order: 3,
      prompt: "What should function as the final authority for faith and life?",
      options: ["Changing feelings", "Personal experience alone", "Popular opinion", "God's revealed Word"],
      correctIndex: 3,
      explanation: "Feelings and experiences must be evaluated by Scripture rather than used to establish truth.",
    },
    {
      order: 4,
      prompt: "What is the purpose of biblical meditation?",
      options: ["To empty the mind of all content", "To move the Word from reading into thought and practice", "To replace careful study", "To create private interpretations"],
      correctIndex: 1,
      explanation: "Meditation helps the Word shape how the believer thinks, believes, and lives.",
    },
    {
      order: 5,
      prompt: "How should Scripture be interpreted?",
      options: ["Carefully, contextually, and with Christ at the center", "According to the strongest emotion in the moment", "Without reference to surrounding passages", "Only through isolated phrases"],
      correctIndex: 0,
      explanation: "Discernment requires careful attention to context and a Christ-centered reading of Scripture.",
    },
  ],
  4: [
    {
      order: 1,
      prompt: "Why is the Holy Spirit essential to Christian life?",
      options: ["He replaces the need for Scripture", "The Christian life is designed to be lived by His power rather than human effort alone", "He is needed only for public ministry", "He removes all need for daily choices"],
      correctIndex: 1,
      explanation: "The Christian life cannot be sustained by willpower alone; believers are called to depend on the Spirit.",
    },
    {
      order: 2,
      prompt: "What does Parakletos teach about the Holy Spirit?",
      options: ["He is an impersonal force", "He is only a symbol of courage", "He is a divine Person who comes alongside believers", "He is available only to church leaders"],
      correctIndex: 2,
      explanation: "The Holy Spirit is a divine Person who comforts, helps, counsels, and fellowships with believers.",
    },
    {
      order: 3,
      prompt: "What does the indwelling of the Spirit mean?",
      options: ["God is present only in church gatherings", "The Spirit takes residence within the believer", "Believers must search for a distant God", "Spiritual life depends on external rituals"],
      correctIndex: 1,
      explanation: "By the Holy Spirit, God lives within the believer and brings New Covenant life into daily experience.",
    },
    {
      order: 4,
      prompt: "How does the Holy Spirit guide believers?",
      options: ["In ways that contradict Scripture", "Only through dramatic public signs", "From within and consistently with God's revealed Word", "By eliminating the need for wisdom"],
      correctIndex: 2,
      explanation: "The Spirit's inward guidance remains consistent with the truth God has revealed in Scripture.",
    },
    {
      order: 5,
      prompt: "What is a central purpose of the baptism and power of the Holy Spirit?",
      options: ["Supernatural empowerment for witness and service", "Personal status above other believers", "Freedom from accountability", "Recognition without character"],
      correctIndex: 0,
      explanation: "The Spirit empowers believers for effective witness, supernatural living, and service to God's purposes.",
    },
  ],
  5: [
    {
      order: 1,
      prompt: "Where does the believer's spiritual authority begin?",
      options: ["Personal intensity", "Union with Christ", "Public recognition", "Length of prayer"],
      correctIndex: 1,
      explanation: "Spiritual authority is not manufactured by the believer; it flows from union with Christ.",
    },
    {
      order: 2,
      prompt: "What does it mean to pray in the name of Jesus?",
      options: ["Add a required phrase without understanding", "Attempt to persuade a reluctant God", "Pray in alignment with His authority, character, will, and finished work", "Rely on volume to make prayer effective"],
      correctIndex: 2,
      explanation: "The name of Jesus represents His authority and character, not a religious formula.",
    },
    {
      order: 3,
      prompt: "How should being seated with Christ affect prayer?",
      options: ["Believers pray from Christ's victory and finished work", "Believers pray to earn a spiritual position", "Believers avoid direct requests", "Believers depend on anxiety for urgency"],
      correctIndex: 0,
      explanation: "The believer shares Christ's position and therefore prays from victory and rest, not to achieve victory.",
    },
    {
      order: 4,
      prompt: "Why does the manual distinguish different kinds of prayer?",
      options: ["Every prayer operates by identical principles", "Different purposes call for appropriate expressions of prayer", "Only one form of prayer is valid", "Prayer categories replace faith"],
      correctIndex: 1,
      explanation: "Understanding each kind of prayer helps believers pray with clarity according to its purpose and principles.",
    },
    {
      order: 5,
      prompt: "What characterizes earnest prayer?",
      options: ["Emotional desperation without faith", "Volume and length alone", "Focused, sincere, faith-filled conviction", "Pressure intended to change God's character"],
      correctIndex: 2,
      explanation: "Earnest prayer may be intense, but its effectiveness comes from faith rather than emotional striving.",
    },
  ],
  6: [
    {
      order: 1,
      prompt: "Where does biblical purpose originate?",
      options: ["In competition with others", "In public opportunity", "In God", "In personal anxiety"],
      correctIndex: 2,
      explanation: "Purpose begins with God and unfolds through relationship, obedience, grace, and trust in His timing.",
    },
    {
      order: 2,
      prompt: "What comes before assignment in a healthy understanding of calling?",
      options: ["Visibility", "Belonging and identity", "A large platform", "Comparison"],
      correctIndex: 1,
      explanation: "Identity precedes assignment. Secure belonging allows purpose to flow from relationship rather than a need to prove worth.",
    },
    {
      order: 3,
      prompt: "Why does faithfulness before platform matter?",
      options: ["Small assignments have no lasting value", "Private faithfulness prepares a person for greater responsibility", "Visibility creates character automatically", "Calling begins only after recognition"],
      correctIndex: 1,
      explanation: "God often develops public usefulness through faithful stewardship of present and unseen assignments.",
    },
    {
      order: 4,
      prompt: "How can preparation differ from meaningless delay?",
      options: ["Preparation develops capacity for future responsibility", "Preparation always proves the calling was abandoned", "Preparation removes the need for grace", "Preparation is valuable only when visible"],
      correctIndex: 0,
      explanation: "Preparation can protect purpose by developing the maturity and capacity needed to sustain future assignments.",
    },
    {
      order: 5,
      prompt: "What is a major danger of comparison?",
      options: ["It clarifies personal assignment", "It redirects attention from your assignment to someone else's", "It produces lasting contentment", "It strengthens trust in God's timing"],
      correctIndex: 1,
      explanation: "Comparison distracts from personal calling and can produce competition, anxiety, and loss of focus.",
    },
  ],
  7: [
    {
      order: 1,
      prompt: "What is biblical stewardship?",
      options: ["Ownership without accountability", "Faithful management of what belongs to God", "A subject limited to giving money", "Control based on personal preference"],
      correctIndex: 1,
      explanation: "God is Owner; believers are responsible for faithfully managing what He entrusts to them.",
    },
    {
      order: 2,
      prompt: "Which areas are included in stewardship?",
      options: ["Finances alone", "Only public ministry gifts", "Time, relationships, gifts, influence, resources, and opportunities", "Only possessions given to church"],
      correctIndex: 2,
      explanation: "The manual presents stewardship as the faithful management of every area of life entrusted by God.",
    },
    {
      order: 3,
      prompt: "What does faithfulness in small things develop?",
      options: ["Readiness for greater responsibility", "Freedom from accountability", "A right to public recognition", "Ownership of God's resources"],
      correctIndex: 0,
      explanation: "Faithfulness in current and seemingly small responsibilities prepares the believer to carry more.",
    },
    {
      order: 4,
      prompt: "What distinguishes Kingdom economics from fear-based worldly thinking?",
      options: ["Scarcity and self-protection", "Accumulation as the only goal", "Trust, stewardship, generosity, obedience, and purpose", "Avoidance of practical planning"],
      correctIndex: 2,
      explanation: "Kingdom economics are shaped by trust in God and the purposeful, generous stewardship of increase.",
    },
    {
      order: 5,
      prompt: "How should believers understand everyday environments?",
      options: ["As separate from spiritual mission", "As potential mission fields where Christ is represented", "As distractions from meaningful service", "As valuable only when publicly visible"],
      correctIndex: 1,
      explanation: "Missional living recognizes homes, workplaces, communities, and relationships as places where believers are sent to represent Christ.",
    },
  ],
};
