import { Award, Pause, Play, ShieldOff } from "lucide-react";
import { issueCertificate, setEnrollmentStatus } from "@/app/admin/students/actions";
import { AdminEmpty, AdminHeader, StatusBadge } from "@/components/admin-ui";
import { requireStaff } from "@/lib/auth";
import { db } from "@/lib/db";
import { SITE_CONFIG } from "@/lib/site-config";

export default async function StudentsPage() {
  const staff = await requireStaff();
  const program = await db.program.findUnique({ where: { slug: SITE_CONFIG.slug }, include: { modules: { where: { status: "PUBLISHED" }, include: { lessons: { where: { status: "PUBLISHED" }, select: { id: true } } } } } });
  const lessonIds = program?.modules.flatMap((module) => module.lessons.map((lesson) => lesson.id)) ?? [];
  const enrollments = await db.enrollment.findMany({ where: { programId: program?.id }, include: { user: { include: { lessonProgress: { where: { lessonId: { in: lessonIds } }, select: { lessonId: true } }, assessmentAttempts: { where: { status: "PASSED", assessment: { module: { programId: program?.id } } }, distinct: ["assessmentId"], select: { assessmentId: true } } } }, program: { select: { name: true } } }, orderBy: { enrolledAt: "desc" } });
  const certificates = program ? await db.certificate.findMany({ where: { programId: program.id }, select: { studentId: true, serial: true } }) : [];
  const certificateByStudent = new Map(certificates.map((item) => [item.studentId, item.serial]));
  return <div className="mx-auto max-w-[1320px] px-4 py-9 md:px-8 md:py-12 xl:px-12"><AdminHeader eyebrow="Enrollment" title="Students" description="See who has access, monitor module completion, pause access, and issue completion records." /><div className="mt-9 overflow-x-auto rounded-2xl border border-black/10 bg-white/65">{enrollments.length === 0 ? <AdminEmpty>No students are enrolled yet.</AdminEmpty> : <table className="w-full min-w-[940px] text-left text-sm"><thead className="border-b border-black/8 text-[0.6rem] font-extrabold tracking-[0.12em] text-[var(--ink-soft)]/55 uppercase"><tr><th className="p-4">Student</th><th className="p-4">Access</th><th className="p-4">Lessons</th><th className="p-4">Checkpoints</th><th className="p-4">Enrolled</th><th className="p-4">Actions</th></tr></thead><tbody>{enrollments.map((enrollment) => { const certificate = certificateByStudent.get(enrollment.userId); const statusTone = enrollment.status === "ACTIVE" || enrollment.status === "COMPLETED" ? "good" : enrollment.status === "PAUSED" ? "warn" : "bad"; return <tr key={enrollment.id} className="border-b border-black/6 align-top last:border-0"><td className="p-4"><strong className="block">{enrollment.user.fullName}</strong><span className="mt-1 block text-xs text-[var(--ink-soft)]/60">{enrollment.user.email}</span>{certificate && <span className="mt-2 block text-[0.62rem] font-extrabold text-[var(--forest)]">Certificate {certificate}</span>}</td><td className="p-4"><StatusBadge tone={statusTone}>{enrollment.status}</StatusBadge></td><td className="p-4 font-extrabold">{enrollment.user.lessonProgress.length} / {lessonIds.length}</td><td className="p-4 font-extrabold">{enrollment.user.assessmentAttempts.length} / {program?.modules.length ?? 0}</td><td className="p-4 text-xs text-[var(--ink-soft)]/65">{enrollment.enrolledAt.toLocaleDateString()}</td><td className="p-4">{staff.role === "ADMIN" && <div className="flex flex-wrap gap-2">{enrollment.status === "ACTIVE" && <form action={setEnrollmentStatus.bind(null, enrollment.id, "PAUSED")}><button className="button-quiet !min-h-9 !px-2"><Pause size={14} /> Pause</button></form>}{enrollment.status === "PAUSED" && <form action={setEnrollmentStatus.bind(null, enrollment.id, "ACTIVE")}><button className="button-quiet !min-h-9 !px-2"><Play size={14} /> Restore</button></form>}{enrollment.status !== "REVOKED" && enrollment.status !== "COMPLETED" && <form action={setEnrollmentStatus.bind(null, enrollment.id, "REVOKED")}><button className="button-quiet !min-h-9 !px-2 text-[var(--clay)]"><ShieldOff size={14} /> Revoke</button></form>}{enrollment.status === "COMPLETED" && !certificate && <form action={issueCertificate.bind(null, enrollment.id)}><button className="button-secondary !min-h-9 !px-3"><Award size={14} /> Issue certificate</button></form>}</div>}</td></tr>; })}</tbody></table>}</div></div>;
}
